FROM mysql:5.6.43
RUN apt-get update -y
RUN apt-get upgrade -y
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt install -y vim curl rsync htop
RUN apt install mysql-server -y
COPY config/deploy-db.sh /tmp/
COPY config/drupal-dump.sql /tmp/


